# .github/workflows/keep-repl-alive.yml

name: Keep Repl Alive

# 이 워크플로우를 수동으로도 실행할 수 있고,
# 5분마다 크론 스케줄로 자동 실행합니다.
on:
  workflow_dispatch:    # ← 수동 실행용 버튼 활성화
  schedule:
    - cron: '*/5 * * * *'

jobs:
  wake_repl:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit Keep-Alive URL
        run: |
          curl -m 10 https://32605038-036c-4f02-b48b-496cd74e0ba2-00-2hz4yb0kyc88v.pike.replit.dev/ || true
